<?php 

/*
 * Aegir Services Schema
 */
function hosting_services_schema(){
  $schema['hosting_services_platforms'] = array(
    'description' => t('States whether or not this platform can be used to create a site via services api'),
    'fields' => array(
      'vid' => array(
        'type' => 'int',
        'not null' => TRUE,
      ),
      'nid' => array(
        'type' => 'int',
        'not null' => TRUE
      ),			
     )
	);
	
  return $schema;
}
